language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.6"
install:
  - pip install -e .[test]
  - pip install coveralls
script:
  - python setup.py -q test --addopts "--cov"
after_success:
  - coveralls
